# values/argocd-values.yaml

server:
  ingress:
    enabled: false

applicationSet:
  enabled: true
  installCRDs: true

controller:
  resources:
    requests:
      cpu:    "50m"
      memory: "128Mi"

repoServer:
  resources:
    requests:
      cpu:    "50m"
      memory: "128Mi"
  initContainers:
    - name: download-tools
      image: alpine:3.20
      command: ["sh", "-c"]
      args:
        - |
          set -euo pipefail
          cd /var/run/docker-credential-gcr
          # grab the current helper (v2.1.30 is the latest as of 2025-07-31)
          wget -qO- \
            https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v2.1.30/docker-credential-gcr_linux_amd64-2.1.30.tar.gz \
            | tar xz
          # write a Docker config that tells helm (via docker library) how to fetch tokens
          PATH=.:$PATH HOME=/var/run/config \
            ./docker-credential-gcr configure-docker
          # allow the main container (non-root user) to read the file
          chmod 0644 /var/run/config/.docker/config.json
      volumeMounts:
        - name: docker-credential-gcr
          mountPath: /var/run/docker-credential-gcr
        - name: docker-config
          mountPath: /var/run/config/.docker
  volumeMounts:
    - name: docker-credential-gcr
      mountPath: /usr/local/bin/docker-credential-gcr
      subPath: docker-credential-gcr
      readOnly: true
    - name: docker-config
      mountPath: /home/argocd/.docker
      readOnly: true
  volumes:
    - name: docker-credential-gcr
      emptyDir: {}
    - name: docker-config
      emptyDir: {}

dex:
  enabled: false

crds:
  install: true

