# values/argocd-values.yaml

server:
  ingress:
    enabled: false

applicationSet:
  enabled: true
  installCRDs: true

controller:
  resources:
    requests:
      cpu:    "50m"
      memory: "128Mi"

repoServer:
  resources:
    requests:
      cpu:    "50m"
      memory: "128Mi"

dex:
  enabled: false

crds:
  install: true

configs.secret.createSecret: true
configs.secret.argocdServerAdminPassword: "$2a$10$SZW7dXFVhVX4wIa0SxIBjeZES26nZBHQLbj3oUfvE9s/D6GtOp5je"