# values/argocd-values.yaml

server:
  ingress:
    enabled: false

applicationSet:
  enabled: true
  installCRDs: true

controller:
  resources:
    requests:
      cpu:    "50m"
      memory: "128Mi"

repoServer:
  resources:
    requests:
      cpu:    "50m"
      memory: "128Mi"
  initContainers:
  - name: download-tools
    image: alpine:3
    command: [ sh, -c ]
    args:
    - |
      cd /var/run/docker-credential-gcr
      wget -qO - https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v2.1.8/docker-credential-gcr_linux_amd64-2.1.8.tar.gz | tar xz
      PATH=.:$PATH HOME=/var/run/config docker-credential-gcr configure-docker
      chmod +r /var/run/config/.docker/config.json
    volumeMounts:
    - mountPath: /var/run/docker-credential-gcr
      name: docker-credential-gcr
    - mountPath: /var/run/config/.docker
      name: docker-config
  volumeMounts:
  - mountPath: /usr/local/bin/docker-credential-gcr
    name: docker-credential-gcr
    subPath: docker-credential-gcr
    readOnly: true
  - mountPath: /home/argocd/.docker
    name: docker-config
    readOnly: true
  volumes:
  - emptyDir: {}
    name: docker-credential-gcr
  - emptyDir: {}
    name: docker-config

dex:
  enabled: false

crds:
  install: true

