name: Terraform


on:
  push:
    branches:
      - main
  pull_request: {}

env:
  TF_VAR_project_id: ${{ secrets.GCP_PROJECT }}

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }
    steps:
      - uses: actions/checkout@v4

      # Auth via Workload Identity Federation (new SA just for infra)
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_PROVIDER }}
          service_account: tf-infra@${{ env.TF_VAR_project_id }}.iam.gserviceaccount.com

      - uses: google-github-actions/setup-gcloud@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.7.5 }

      - name: Terraform init
        run: terraform init

      - name: Terraform fmt & validate
        run: |
          terraform fmt -check
          terraform validate

      - name: Terraform plan
        run: terraform plan -out=plan.out

      - name: Upload plan
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan
          path: plan.out

  apply:
    needs: plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }
    steps:
      - uses: actions/download-artifact@v4
        with: { name: tf-plan }
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_PROVIDER }}
          service_account: tf-infra@${{ env.TF_VAR_project_id }}.iam.gserviceaccount.com
      - uses: google-github-actions/setup-gcloud@v2
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.7.5 }
      - name: Terraform apply
        run: terraform apply -auto-approve plan.out
