name: Terraform Destroy (Manual)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type DESTROY to confirm"
        required: true

env:
  PROJECT: ${{ secrets.GCP_PROJECT }}
  TF_BUCKET: ${{ secrets.GCP_PROJECT }}-tfstate
  REGION: europe-west2

jobs:
  destroy:
    if: github.event.inputs.confirm == 'DESTROY'
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_PROVIDER }}
          service_account: tf-infra@${{ env.PROJECT }}.iam.gserviceaccount.com

      - uses: google-github-actions/setup-gcloud@v2

      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.7.5 }

      - name: Terraform init
        run: terraform init -backend-config="bucket=$TF_BUCKET"

      - name: Terraform destroy
        run: TF_LOG=DEBUG terraform destroy -auto-approve -input=false
